all:
  hosts:
    Ansible:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3.12

    Audiobok:
      ansible_host: 192.168.11.33
      ansible_port: 27912
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Jellyfin:
      ansible_host: 192.168.11.22
      ansible_port: 52731
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Kafka:
      ansible_host: 192.168.11.80
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Prometheus:
      ansible_host: 192.168.11.35
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    ClickHouse:
      ansible_host: 192.168.11.128
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    OpenSearch:
      ansible_host: 192.168.11.145
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Netbox:
      ansible_host: 192.168.11.77
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Grafana:
      ansible_host: 192.168.11.111
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12


    Home-server:
      ansible_host: 192.168.11.89
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3.12

    Terraform:
      ansible_host: 192.168.11.10
      ansible_port: 22
      ansible_user: sheremet
      ansible_connection: ssh
      ansible_python_interpreter: /usr/bin/python3
