all:
  children:

    local:
      hosts:
        Ansible:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3.12

    media:
      hosts:
        Audiobook:
          ansible_host: 192.168.11.33

        Jellyfin:
          ansible_host: 192.168.11.22

        Home-server:
          ansible_host: 192.168.11.89

    monitoring:
      hosts:
        Prometheus:
          ansible_host: 192.168.11.45

        Grafana:
          ansible_host: 192.168.11.111

    databases:
      hosts:
        ClickHouse:
          ansible_host: 192.168.11.128

        OpenSearch:
          ansible_host: 192.168.11.145

    infrastructure:
      hosts:
        Kafka-1:
          ansible_host: 192.168.11.80

        Kafka-2:
          ansible_host: 192.168.11.81

        Kafka-3:
          ansible_host: 192.168.11.82

        Netbox:
          ansible_host: 192.168.11.77

        Terraform:
          ansible_host: 192.168.11.10



  vars:
    ansible_user: sheremet
    ansible_connection: ssh
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3.12
